# Generated by Codex on 2026-03-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='mood_source',
            field=models.CharField(default='self_report', max_length=50),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tasks_planned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='tasks_completion_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='days_in_stress',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BurnMapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='burnmap_result', to='api.checkin')),
            ],
        ),
    ]
